$:
  vscode:
    - docker:
        image: cnbcool/default-dev-env:latest
      services:
        - vscode
        - docker
      imports: 
        - https://cnb.cool/wymix.top/nav_sync/-/blob/main/env.prod.yml
      # 开发环境启动后会执行的任务
      stages:
        - name: install nvm
          script: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"  
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install --lts
            npm install -g @anthropic-ai/claude-code --registry=https://registry.npmmirror.com
        - name: init claude.json
          script: |
            cat > ~/.claude.json <<EOF
            {
              "hasCompletedOnboarding": true
            }
            EOF
        - name: config baseUrl & apikey
          script: |
            mkdir ~/.claude
            cat > ~/.claude/settings.json <<EOF
            {
              "env": {
                "ANTHROPIC_BASE_URL": "$CUSTOM_ANTHROPIC_BASE_URL",
                "ANTHROPIC_AUTH_TOKEN": "$CUSTOM_ANTHROPIC_API_KEY",
                "ANTHROPIC_MODEL": "mimo-v2.5[1M]",
                "ANTHROPIC_DEFAULT_SONNET_MODEL": "mimo-v2.5[1M]",
                "ANTHROPIC_DEFAULT_OPUS_MODEL": "mimo-v2.5[1M]",
                "ANTHROPIC_DEFAULT_HAIKU_MODEL": "mimo-v2.5"
              }
            }
            EOF